class HomePageLocators:
    HEADER_TITLE = "h1:text-is('Car Selling Platform')"
    AVAILABLE_CARS_TITLE = "h2:text-is('Available Cars')"
    ADD_NEW_CAR_LINK = "a[href='/add-car']"
    FILTER_BRAND_INPUT = "input[name='brand']"
    FILTER_MIN_PRICE_INPUT = "input[name='minPrice']"
    FILTER_MAX_PRICE_INPUT = "input[name='maxPrice']"
    APPLY_FILTERS_BUTTON = "button:has-text('Apply Filters')"
    LOADING_TEXT = "text=Loading cars..."
    ERROR_BANNER = "div.bg-red-100"
    EMPTY_STATE_TEXT = "text=No cars found. Be the first to list one!"
    CAR_CARD = "div.bg-white.rounded-lg.shadow-md"
    CAR_CARD_TITLE = "h3"
    VIEW_DETAILS_LINK = "a:has-text('View Details')"


class AddCarPageLocators:
    PAGE_TITLE = "h1:text-is('List Your Car for Sale')"
    FORM = "form"
    ERROR_BANNER = "div.bg-red-100"
    TITLE_INPUT = "input[name='title']"
    BRAND_INPUT = "input[name='brand']"
    MODEL_INPUT = "input[name='model']"
    YEAR_INPUT = "input[name='year']"
    PRICE_INPUT = "input[name='price']"
    MILEAGE_INPUT = "input[name='mileage']"
    DESCRIPTION_TEXTAREA = "textarea[name='description']"
    IMAGE_URL_INPUT = "input[type='url']"
    SELLER_NAME_INPUT = "input[name='seller.name']"
    SELLER_EMAIL_INPUT = "input[name='seller.email']"
    SELLER_PHONE_INPUT = "input[name='seller.phone']"
    SELLER_CITY_INPUT = "input[name='seller.city']"
    CREATE_LISTING_BUTTON = "button[type='submit']"
    CANCEL_BUTTON = "button:has-text('Cancel')"


class CarDetailsPageLocators:
    BACK_TO_LISTINGS_BUTTON = "button:has-text('Back to Listings')"
    LOADING_TEXT = "text=Loading car details..."
    ERROR_BANNER = "div.bg-red-100"
    NOT_FOUND_TEXT = "text=Car not found"
    TITLE = "h1"
    DESCRIPTION_TEXT = "div.mb-6 p.text-gray-600.leading-relaxed"
    MARK_AS_SOLD_BUTTON = "button:has-text('Mark as Sold')"
    DELETE_LISTING_BUTTON = "button:has-text('Delete Listing')"
    SOLD_BADGE = "p:text-is('This car has been sold')"
